server:
  host: "0.0.0.0"
  port: 8000
  debug: true

audio:
  sample_rate: 16000             # 需要适配 vad 模型的采样率
  channels: 1                    # 蓝牙回环通常在硬件层只暴露 1 个通道给录制
  device_index: null             # 如果为null则自动寻找回环设备
  save_path: "backend/tests/temp_audio"
  save_temp: true                # 是否进行中间音频存储
  min_silence_time: 0.8          # 最小静音时长（秒）
  max_silence_time: 1            # 最大静音时长（秒）
  min_segment_time: 0.5          # 最小语音分段时长（秒），送至ASR模型
  max_segment_time: 15           # 最大语音分段时长（秒），送至ASR模型
  vad_threshold: 0.3             # 静音阈值（0-1）
  vad_model_path: "backend/models/silero_vad.onnx"

asr:
  model_size: "base"  # 如 "base","small","medium"
  device: "cpu"       # 如 "cpu","gpu"
  compute_type: "int8" # "int8", "float16" (cuda下常用)

models:
  whisper_model_path: "backend/models/whisper-tiny"
  ocr_model_dir: "backend/models/paddle_ocr"
  compute_type: "int8" # CPU 优化

vision:
  fps: 5
  roi_regions: # 鹅鸭杀头像高亮区域坐标示例
    - [100, 200, 50, 50]